// <auto-generated />
using ApiCountriesV7.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ApiCountriesV7.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ApiCountriesV7.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlphaCode2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AlphaCode3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Independent")
                        .HasColumnType("bit");

                    b.Property<string>("LinkSubdivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumericCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlphaCode2 = "AF",
                            AlphaCode3 = "AFG",
                            Independent = true,
                            LinkSubdivision = "https://en.wikipedia.org/wiki/ISO_3166-2:AF",
                            Name = "Afghanistan",
                            NumericCode = 4
                        },
                        new
                        {
                            Id = 2,
                            AlphaCode2 = "AX",
                            AlphaCode3 = "ALA",
                            Independent = false,
                            LinkSubdivision = "https://en.wikipedia.org/wiki/ISO_3166-2:AX",
                            Name = "Aland Islands",
                            NumericCode = 248
                        },
                        new
                        {
                            Id = 3,
                            AlphaCode2 = "AL",
                            AlphaCode3 = "ALB",
                            Independent = true,
                            LinkSubdivision = "https://en.wikipedia.org/wiki/ISO_3166-2:AL",
                            Name = "Albania",
                            NumericCode = 8
                        });
                });

            modelBuilder.Entity("ApiCountriesV7.Models.Subdivision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Subdivisions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "AF-BDS",
                            CountryId = 1,
                            Name = "Badakhshān"
                        },
                        new
                        {
                            Id = 2,
                            Code = "AF-BDG",
                            CountryId = 1,
                            Name = "Bādghīs"
                        },
                        new
                        {
                            Id = 3,
                            Code = "AF-KAB",
                            CountryId = 1,
                            Name = "Kābul"
                        },
                        new
                        {
                            Id = 4,
                            Code = "AL-01",
                            CountryId = 3,
                            Name = "Berat"
                        },
                        new
                        {
                            Id = 5,
                            Code = "AL-04",
                            CountryId = 3,
                            Name = "Fier"
                        });
                });

            modelBuilder.Entity("ApiCountriesV7.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "test@domain.com",
                            Password = "E99A18C428CB38D5F260853678922E03"
                        });
                });

            modelBuilder.Entity("ApiCountriesV7.Models.Subdivision", b =>
                {
                    b.HasOne("ApiCountriesV7.Models.Country", null)
                        .WithMany("Subdivisions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiCountriesV7.Models.Country", b =>
                {
                    b.Navigation("Subdivisions");
                });
#pragma warning restore 612, 618
        }
    }
}
